import { VehicleType, WashService } from "./types";

export const DEFAULT_VEHICLE_TYPES: VehicleType[] = [
  {
    id: "small",
    name: "Light Vehicle",
    examples: "Automobile, Minibus, Pickup",
    standard_minutes: 45,
    workers_required: 2,
    default_soap_ml: 180,
    detergent_cost_etb: 33.84,
    default_price: 350,
    color: "#2dd4c8",
  },
  {
    id: "medium",
    name: "Medium Vehicle",
    examples: "Sino Truck, Isuzu, Mid Bus",
    standard_minutes: 120,
    workers_required: 2,
    default_soap_ml: 250,
    detergent_cost_etb: 47.0,
    default_price: 900,
    color: "#f59e0b",
  },
  {
    id: "large",
    name: "Heavy Vehicle",
    examples: "Trailer",
    standard_minutes: 180,
    workers_required: 2,
    default_soap_ml: 500,
    detergent_cost_etb: 94.0,
    default_price: 1800,
    color: "#a78bfa",
  },
];

export const DEFAULT_WASH_SERVICES: WashService[] = [
  {
    id: "exterior",
    name: "Standard Exterior Wash",
    category: "standard",
    description: "High-pressure foam wash, wheel clean, hand dry",
    price_small: 350,
    price_medium: 900,
    price_large: 1800,
    extra_soap_ml: 0,
    active: true,
  },
  {
    id: "full_wash",
    name: "Full Wash (Body + Engine + Underbody)",
    category: "standard",
    description: "Full body shampoo, undercarriage degrease, engine bay wash",
    price_small: 550,
    price_medium: 1400,
    price_large: 2600,
    extra_soap_ml: 80,
    active: true,
  },
  {
    id: "engine_steam",
    name: "Engine Steam Clean",
    category: "addon",
    description: "High-temp degreasing and electronic component care",
    price_small: 250,
    price_medium: 450,
    price_large: 700,
    extra_soap_ml: 50,
    active: true,
  },
  {
    id: "interior_detail",
    name: "Interior Deep Clean & Vacuum",
    category: "addon",
    description: "Seat extraction, dashboard UV protectant, carpet shampoo",
    price_small: 300,
    price_medium: 600,
    price_large: 900,
    extra_soap_ml: 40,
    active: true,
  },
  {
    id: "wax_polish",
    name: "Hand Wax & Paint Sealant",
    category: "addon",
    description: "Carnuba wax coating for gloss finish and water repellency",
    price_small: 350,
    price_medium: 700,
    price_large: 1100,
    extra_soap_ml: 30,
    active: true,
  },
  {
    id: "tire_shine",
    name: "Tire & Trim Dressing",
    category: "addon",
    description: "Silicone-free deep black tire shine and UV protection",
    price_small: 100,
    price_medium: 200,
    price_large: 300,
    extra_soap_ml: 20,
    active: true,
  },
];
