"use client";
import { createClient } from "./supabase/client";
import { DEFAULT_VEHICLE_TYPES, DEFAULT_WASH_SERVICES } from "./catalog";

// Fallback seed constants are now clean empty datasets (no mock data)
const SEED_INVENTORY: InventoryItem[] = [];
const SEED_SUPPLIERS: Supplier[] = [];
const SEED_PO: PurchaseOrder[] = [];
const SEED_WASHERS: any[] = [];
const SEED_STAFF: Profile[] = [];
const SEED_CUSTOMERS: Customer[] = [];
const SEED_REQUESTS: SoapRequest[] = [];
const SEED_EXPENSES: Expense[] = [];
const SEED_WASHES: WashTransaction[] = [];

// Automatic one-time purge of old mock seed caches from browser localStorage
if (typeof window !== "undefined") {
  const REAL_DATA_KEY = "washos_v4_real_data_only";
  if (!localStorage.getItem(REAL_DATA_KEY)) {
    [
      "washos_inventory",
      "washos_suppliers",
      "washos_purchase_orders",
      "washos_customers",
      "washos_wash_transactions",
      "washos_soap_requests",
      "washos_expenses",
      "washos_staff",
      "washos_washers_stock",
      "washos_notifications",
      "washos_services",
    ].forEach((k) => localStorage.removeItem(k));
    localStorage.setItem(REAL_DATA_KEY, "true");
  }
}
import {
  Customer,
  Expense,
  InventoryItem,
  PaymentMethod,
  Profile,
  PurchaseOrder,
  SoapRequest,
  Supplier,
  WashService,
  WashStatus,
  WashTransaction,
} from "./types";

const STORAGE_KEYS = {
  INVENTORY: "washos_inventory",
  SUPPLIERS: "washos_suppliers",
  PURCHASE_ORDERS: "washos_purchase_orders",
  CUSTOMERS: "washos_customers",
  WASH_TRANSACTIONS: "washos_wash_transactions",
  SOAP_REQUESTS: "washos_soap_requests",
  EXPENSES: "washos_expenses",
  STAFF: "washos_staff",
  WASHERS_STOCK: "washos_washers_stock",
  NOTIFICATIONS: "washos_notifications",
  SERVICES: "washos_services",
};

// Safe browser localStorage helper
function getLocal<T>(key: string, fallback: T): T {
  if (typeof window === "undefined") return fallback;
  try {
    const raw = localStorage.getItem(key);
    if (!raw) {
      localStorage.setItem(key, JSON.stringify(fallback));
      return fallback;
    }
    return JSON.parse(raw);
  } catch {
    return fallback;
  }
}

function setLocal<T>(key: string, value: T): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(key, JSON.stringify(value));
    window.dispatchEvent(new Event("washos_data_change"));
  } catch (e) {
    console.error("Local storage write error:", e);
  }
}

/* Fast resilient helper: queries Supabase with timeout and falls back to local storage only on failure/null */
async function supabaseCall<T>(
  supabasePromise: Promise<{ data: any; error: any }>,
  localFallback: () => T,
  timeoutMs = 5000
): Promise<T> {
  try {
    const timeoutPromise = new Promise<{ data: null; error: { message: string } }>((resolve) =>
      setTimeout(() => resolve({ data: null, error: { message: "timeout" } }), timeoutMs)
    );
    const { data, error } = await Promise.race([supabasePromise, timeoutPromise]);
    if (error || data === null || data === undefined) {
      return localFallback();
    }
    return data as T;
  } catch {
    return localFallback();
  }
}

/* ─────────────────────────────────────────────────────────────
   DATA STORE INTERFACE
   ───────────────────────────────────────────────────────────── */

export const DataStore = {
  // ── INVENTORY ──────────────────────────────────────────────
  async getInventory(): Promise<InventoryItem[]> {
    return supabaseCall<InventoryItem[]>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase.from("inventory").select("*").order("product_name");
        if (data && !error) {
          setLocal(STORAGE_KEYS.INVENTORY, data);
        }
        return { data: data as InventoryItem[] | null, error };
      })(),
      () => getLocal<InventoryItem[]>(STORAGE_KEYS.INVENTORY, SEED_INVENTORY)
    );
  },

  async createInventoryItem(item: Omit<InventoryItem, "id" | "status">): Promise<InventoryItem> {
    const totalMl = Number(item.total_ml);
    const minMl = Number(item.min_stock_ml);
    const status: "ok" | "low" | "critical" =
      totalMl <= minMl * 0.4 ? "critical" : totalMl <= minMl ? "low" : "ok";

    return supabaseCall<InventoryItem>(
      (async () => {
        const supabase = createClient();
        // Omit id (UUID generated by DB) and status (GENERATED ALWAYS column in DB)
        const { data, error } = await supabase
          .from("inventory")
          .insert({
            product_name: item.product_name,
            category: item.category,
            total_ml: totalMl,
            min_stock_ml: minMl,
            supplier: item.supplier || null,
            supplier_id: item.supplier_id || null,
            batch_number: item.batch_number || null,
            purchase_date: (item as any).purchase_date || null,
            expiry_date: item.expiry_date || null,
            unit_cost: item.unit_cost ? Number(item.unit_cost) : 0,
            cost: item.cost ? Number(item.cost) : 0,
          })
          .select()
          .single();

        if (data) {
          const created = data as InventoryItem;
          const items = getLocal<InventoryItem[]>(STORAGE_KEYS.INVENTORY, SEED_INVENTORY);
          setLocal(STORAGE_KEYS.INVENTORY, [created, ...items.filter((i) => i.id !== created.id)]);
          return { data: created, error: null };
        }
        return { data: null, error };
      })(),
      () => {
        const fallbackItem: InventoryItem = {
          id: "inv-" + Date.now(),
          ...item,
          total_ml: totalMl,
          min_stock_ml: minMl,
          status,
        };
        const items = getLocal<InventoryItem[]>(STORAGE_KEYS.INVENTORY, SEED_INVENTORY);
        setLocal(STORAGE_KEYS.INVENTORY, [fallbackItem, ...items]);
        return fallbackItem;
      }
    );
  },

  async updateInventoryItem(id: string, updates: Partial<InventoryItem>): Promise<void> {
    await supabaseCall(
      (async () => {
        const supabase = createClient();
        // Omit status because it is a generated stored column in PostgreSQL
        const { status: _st, ...dbUpdates } = updates;
        const { error } = await supabase.from("inventory").update(dbUpdates).eq("id", id);
        return { data: null, error };
      })(),
      () => {
        const items = getLocal<InventoryItem[]>(STORAGE_KEYS.INVENTORY, SEED_INVENTORY);
        const updated = items.map((i) => {
          if (i.id === id) {
            const next = { ...i, ...updates };
            const total = Number(next.total_ml);
            const min = Number(next.min_stock_ml);
            next.status = total <= min * 0.4 ? "critical" : total <= min ? "low" : "ok";
            return next;
          }
          return i;
        });
        setLocal(STORAGE_KEYS.INVENTORY, updated);
        return undefined;
      }
    );
  },

  async deleteInventoryItem(id: string): Promise<void> {
    await supabaseCall(
      (async () => {
        const supabase = createClient();
        const { error } = await supabase.from("inventory").delete().eq("id", id);
        return { data: null, error };
      })(),
      () => {
        const items = getLocal<InventoryItem[]>(STORAGE_KEYS.INVENTORY, SEED_INVENTORY);
        setLocal(STORAGE_KEYS.INVENTORY, items.filter((i) => i.id !== id));
        return undefined;
      }
    );
  },

  // ── SUPPLIERS ──────────────────────────────────────────────
  async getSuppliers(): Promise<Supplier[]> {
    return supabaseCall<Supplier[]>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase.from("suppliers").select("*").order("name");
        if (data && !error) {
          setLocal(STORAGE_KEYS.SUPPLIERS, data);
        }
        return { data: data as Supplier[] | null, error };
      })(),
      () => getLocal<Supplier[]>(STORAGE_KEYS.SUPPLIERS, SEED_SUPPLIERS)
    );
  },

  async createSupplier(supplier: Omit<Supplier, "id">): Promise<Supplier> {
    return supabaseCall<Supplier>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase
          .from("suppliers")
          .insert({
            name: supplier.name,
            contact: supplier.contact,
            email: supplier.email || null,
            products: supplier.products || null,
            address: supplier.address || null,
            active: supplier.active ?? true,
          })
          .select()
          .single();

        if (data) {
          const created = data as Supplier;
          const list = getLocal<Supplier[]>(STORAGE_KEYS.SUPPLIERS, SEED_SUPPLIERS);
          setLocal(STORAGE_KEYS.SUPPLIERS, [created, ...list.filter((s) => s.id !== created.id)]);
          return { data: created, error: null };
        }
        return { data: null, error };
      })(),
      () => {
        const fallbackSupplier: Supplier = {
          id: "sup-" + Date.now(),
          ...supplier,
        };
        const list = getLocal<Supplier[]>(STORAGE_KEYS.SUPPLIERS, SEED_SUPPLIERS);
        setLocal(STORAGE_KEYS.SUPPLIERS, [fallbackSupplier, ...list]);
        return fallbackSupplier;
      }
    );
  },

  // ── PURCHASE ORDERS ────────────────────────────────────────
  async getPurchaseOrders(): Promise<PurchaseOrder[]> {
    return supabaseCall<PurchaseOrder[]>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase.from("purchase_orders").select("*").order("ordered_at", { ascending: false });
        if (data && !error) {
          setLocal(STORAGE_KEYS.PURCHASE_ORDERS, data);
        }
        return { data: data as PurchaseOrder[] | null, error };
      })(),
      () => getLocal<PurchaseOrder[]>(STORAGE_KEYS.PURCHASE_ORDERS, SEED_PO)
    );
  },

  async createPurchaseOrder(po: {
    supplier_id: string;
    supplier_name: string;
    inventory_id: string | null;
    product_name: string;
    qty_ml: number;
    unit_cost: number;
    notes?: string;
  }): Promise<PurchaseOrder> {
    const total_cost = (po.qty_ml / 1000) * po.unit_cost;
    const poNum = `PO-${Date.now().toString().slice(-4)}`;

    return supabaseCall<PurchaseOrder>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase
          .from("purchase_orders")
          .insert({
            po_number: poNum,
            supplier_id: po.supplier_id || null,
            supplier_name: po.supplier_name,
            inventory_id: po.inventory_id || null,
            product_name: po.product_name,
            qty_ml: Number(po.qty_ml),
            unit_cost: Number(po.unit_cost),
            notes: po.notes || null,
            status: "pending",
          })
          .select()
          .single();

        if (data) {
          const created = data as PurchaseOrder;
          const current = getLocal<PurchaseOrder[]>(STORAGE_KEYS.PURCHASE_ORDERS, SEED_PO);
          setLocal(STORAGE_KEYS.PURCHASE_ORDERS, [created, ...current.filter((p) => p.id !== created.id)]);
          return { data: created, error: null };
        }
        return { data: null, error };
      })(),
      () => {
        const fallbackPO: PurchaseOrder = {
          id: "po-" + Date.now(),
          po_number: poNum,
          status: "pending",
          ordered_at: new Date().toISOString().slice(0, 10),
          received_at: null,
          total_cost,
          ...po,
        };
        const current = getLocal<PurchaseOrder[]>(STORAGE_KEYS.PURCHASE_ORDERS, SEED_PO);
        setLocal(STORAGE_KEYS.PURCHASE_ORDERS, [fallbackPO, ...current]);
        return fallbackPO;
      }
    );
  },

  async receivePurchaseOrder(id: string): Promise<void> {
    await supabaseCall(
      (async () => {
        const supabase = createClient();
        let error: any = null;
        try {
          const { error: poError } = await supabase
            .from("purchase_orders")
            .update({ status: "received", received_at: new Date().toISOString() })
            .eq("id", id);
          if (poError) throw poError;

          const currentPOs = getLocal<PurchaseOrder[]>(STORAGE_KEYS.PURCHASE_ORDERS, SEED_PO);
          const target = currentPOs.find((p) => p.id === id);
          if (target && target.inventory_id) {
            const { data: inv, error: invError } = await supabase
              .from("inventory")
              .select("total_ml")
              .eq("id", target.inventory_id)
              .single();
            if (invError) throw invError;
            if (inv) {
              await supabase
                .from("inventory")
                .update({ total_ml: (inv.total_ml || 0) + target.qty_ml })
                .eq("id", target.inventory_id);
            }
          }
        } catch (err) {
          error = err;
        }
        return { data: null, error };
      })(),
      () => {
        const pos = getLocal<PurchaseOrder[]>(STORAGE_KEYS.PURCHASE_ORDERS, SEED_PO);
        const updatedPOs = pos.map((p) =>
          p.id === id ? { ...p, status: "received" as const, received_at: new Date().toISOString() } : p
        );
        setLocal(STORAGE_KEYS.PURCHASE_ORDERS, updatedPOs);

        const inventory = getLocal<InventoryItem[]>(STORAGE_KEYS.INVENTORY, SEED_INVENTORY);
        const target = pos.find((p) => p.id === id);
        if (target) {
          const updatedInv = inventory.map((item) => {
            if (item.id === target.inventory_id || item.product_name === target.product_name) {
              const newTotal = item.total_ml + target.qty_ml;
              const status: "ok" | "low" | "critical" =
                newTotal <= item.min_stock_ml * 0.4
                  ? "critical"
                  : newTotal <= item.min_stock_ml
                  ? "low"
                  : "ok";
              return { ...item, total_ml: newTotal, status };
            }
            return item;
          });
          setLocal(STORAGE_KEYS.INVENTORY, updatedInv);
        }
        return undefined;
      }
    );
  },

  // ── CUSTOMERS ──────────────────────────────────────────────
  async getCustomers(): Promise<Customer[]> {
    return supabaseCall<Customer[]>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase
          .from("customers")
          .select("id, full_name, phone, notes, created_at, vehicles(count)")
          .order("created_at", { ascending: false });
        if (data) {
          const mapped: Customer[] = (data as any[]).map((c) => ({
            id: c.id,
            full_name: c.full_name,
            phone: c.phone,
            notes: c.notes,
            created_at: c.created_at,
            vehicle_count: Array.isArray(c.vehicles) && c.vehicles[0] ? c.vehicles[0].count : (c.vehicles?.count ?? 1),
          }));
          setLocal(STORAGE_KEYS.CUSTOMERS, mapped);
          return { data: mapped, error };
        }
        return { data: null, error };
      })(),
      () => getLocal<Customer[]>(STORAGE_KEYS.CUSTOMERS, SEED_CUSTOMERS)
    );
  },

  async createCustomer(cust: { full_name: string; phone?: string; notes?: string }): Promise<Customer> {
    return supabaseCall<Customer>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase
          .from("customers")
          .insert({
            full_name: cust.full_name,
            phone: cust.phone || null,
            notes: cust.notes || null,
          })
          .select()
          .single();

        if (data) {
          const createdCust: Customer = {
            id: data.id,
            full_name: data.full_name,
            phone: data.phone,
            notes: data.notes,
            created_at: data.created_at,
            vehicle_count: 1,
          };
          const list = getLocal<Customer[]>(STORAGE_KEYS.CUSTOMERS, SEED_CUSTOMERS);
          setLocal(STORAGE_KEYS.CUSTOMERS, [createdCust, ...list.filter((c) => c.id !== createdCust.id)]);
          return { data: createdCust, error: null };
        }
        return { data: null, error };
      })(),
      () => {
        const fallbackCust: Customer = {
          id: "c-" + Date.now(),
          full_name: cust.full_name,
          phone: cust.phone || null,
          notes: cust.notes || null,
          created_at: new Date().toISOString(),
          vehicle_count: 1,
        };
        const list = getLocal<Customer[]>(STORAGE_KEYS.CUSTOMERS, SEED_CUSTOMERS);
        setLocal(STORAGE_KEYS.CUSTOMERS, [fallbackCust, ...list]);
        return fallbackCust;
      }
    );
  },

  async deleteCustomer(id: string): Promise<void> {
    await supabaseCall(
      (async () => {
        const supabase = createClient();
        const { error } = await supabase.from("customers").delete().eq("id", id);
        return { data: null, error };
      })(),
      () => {
        const customers = getLocal<Customer[]>(STORAGE_KEYS.CUSTOMERS, SEED_CUSTOMERS);
        setLocal(STORAGE_KEYS.CUSTOMERS, customers.filter((c) => c.id !== id));
        return undefined;
      }
    );
  },

  // ── WASH TRANSACTIONS ──────────────────────────────────────
  async getWashTransactions(from?: string, to?: string): Promise<WashTransaction[]> {
    return supabaseCall<WashTransaction[]>(
      (async () => {
        const supabase = createClient();
        let q = supabase
          .from("wash_transactions")
          .select(
            "id, receipt_number, price, soap_used_ml, payment_method, payment_status, services, bay_number, status, started_at, completed_at, actual_minutes, vehicle_type_id, washer_id, profiles(full_name), vehicles(plate, customers(full_name, phone))"
          )
          .order("started_at", { ascending: false });

        if (from) q = q.gte("started_at", `${from}T00:00:00`);
        if (to) q = q.lte("started_at", `${to}T23:59:59`);

        const { data, error } = await q;
        if (data) {
          const mapped: WashTransaction[] = (data as any[]).map((w) => ({
            id: w.id,
            receipt_number: w.receipt_number || "WASH-" + w.id.slice(0, 6).toUpperCase(),
            price: Number(w.price || 0),
            soap_used_ml: Number(w.soap_used_ml || 0),
            payment_method: w.payment_method || "cash",
            payment_status: w.payment_status || "paid",
            services: w.services || ["exterior"],
            bay_number: w.bay_number || 1,
            status: (w.status as WashStatus) || "completed",
            started_at: w.started_at,
            completed_at: w.completed_at,
            actual_minutes: w.actual_minutes,
            vehicle_type_id: w.vehicle_type_id || "small",
            washer_id: w.washer_id,
            washer_name: w.profiles?.full_name || w.washer_name || "Assigned Attendant",
            plate: w.vehicles?.plate || w.plate || "ET-0000",
            customer_name: w.vehicles?.customers?.full_name || w.customer_name || "Guest Customer",
            customer_phone: w.vehicles?.customers?.phone || w.customer_phone,
            commission_amount: Math.round(Number(w.price || 0) * 0.2), // 20% standard attendant commission
          }));
          if (!from && !to) {
            setLocal(STORAGE_KEYS.WASH_TRANSACTIONS, mapped);
          }
          return { data: mapped, error };
        }
        return { data: null, error };
      })(),
      () => {
        const localWashes = getLocal<WashTransaction[]>(STORAGE_KEYS.WASH_TRANSACTIONS, SEED_WASHES);
        if (!from && !to) return localWashes;
        return localWashes.filter((w) => {
          const day = (w.started_at || "").slice(0, 10);
          if (from && day < from) return false;
          if (to && day > to) return false;
          return true;
        });
      }
    );
  },

  async createWashTransaction(
    wash: Omit<WashTransaction, "id" | "started_at" | "completed_at"> & { completed_at?: string | null }
  ): Promise<WashTransaction> {
    return supabaseCall<WashTransaction>(
      (async () => {
        const supabase = createClient();

        // 1. Ensure vehicle exists in database
        let vehicleId = wash.vehicle_id;
        if (!vehicleId && wash.plate) {
          const { data: existingV } = await supabase
            .from("vehicles")
            .select("id")
            .eq("plate", wash.plate.toUpperCase().trim())
            .maybeSingle();

          if (existingV) {
            vehicleId = existingV.id;
          } else {
            const { data: newV } = await supabase
              .from("vehicles")
              .insert({
                plate: wash.plate.toUpperCase().trim(),
                vehicle_type_id: wash.vehicle_type_id || "small",
              })
              .select("id")
              .maybeSingle();
            if (newV) vehicleId = newV.id;
          }
        }

        // 2. Resolve washer UUID (use active profile UUID if mock string ID provided)
        let washerId = wash.washer_id;
        const isUUID = washerId && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(washerId);
        if (!isUUID) {
          const { data: prof } = await supabase.from("profiles").select("id").limit(1).maybeSingle();
          if (prof) washerId = prof.id;
        }

        // 3. Insert into wash_transactions table
        const insertPayload: any = {
          vehicle_id: vehicleId,
          vehicle_type_id: wash.vehicle_type_id || "small",
          washer_id: washerId,
          price: Number(wash.price || 0),
          soap_used_ml: Number(wash.soap_used_ml || 0),
          payment_method: wash.payment_method || "cash",
          payment_status: wash.payment_status || "paid",
          services: wash.services || [],
          bay_number: wash.bay_number || 1,
          status: wash.status || "in_progress",
          actual_minutes: wash.actual_minutes || null,
        };
        if (wash.completed_at) insertPayload.completed_at = wash.completed_at;

        const { data, error } = await supabase
          .from("wash_transactions")
          .insert(insertPayload)
          .select("id, receipt_number, started_at, completed_at, price, soap_used_ml, payment_method, payment_status, status, bay_number, vehicle_type_id, washer_id")
          .single();

        if (data) {
          const createdWash: WashTransaction = {
            id: data.id,
            receipt_number: data.receipt_number || `REC-${data.id.slice(0, 5).toUpperCase()}`,
            plate: wash.plate,
            vehicle_type_id: wash.vehicle_type_id,
            washer_id: wash.washer_id,
            washer_name: wash.washer_name,
            customer_name: wash.customer_name,
            customer_phone: wash.customer_phone,
            price: Number(data.price),
            soap_used_ml: Number(data.soap_used_ml),
            payment_method: data.payment_method as PaymentMethod,
            payment_status: data.payment_status,
            txn_ref: wash.txn_ref,
            commission_amount: Math.round(Number(data.price) * 0.2),
            services: wash.services,
            bay_number: data.bay_number,
            status: data.status as WashStatus,
            started_at: data.started_at,
            completed_at: data.completed_at,
            actual_minutes: wash.actual_minutes,
          };

          const current = getLocal<WashTransaction[]>(STORAGE_KEYS.WASH_TRANSACTIONS, SEED_WASHES);
          setLocal(STORAGE_KEYS.WASH_TRANSACTIONS, [createdWash, ...current.filter((w) => w.id !== createdWash.id)]);

          if (wash.washer_id && wash.soap_used_ml) {
            const washerStocks = getLocal<Record<string, number>>(STORAGE_KEYS.WASHERS_STOCK, {
              "w-1": 750,
              "w-2": 540,
              "w-3": 180,
              "w-4": 620,
            });
            washerStocks[wash.washer_id] = Math.max(0, (washerStocks[wash.washer_id] ?? 800) - wash.soap_used_ml);
            setLocal(STORAGE_KEYS.WASHERS_STOCK, washerStocks);
          }

          return { data: createdWash, error: null };
        }
        return { data: null, error };
      })(),
      () => {
        const current = getLocal<WashTransaction[]>(STORAGE_KEYS.WASH_TRANSACTIONS, SEED_WASHES);
        const fallbackWash: WashTransaction = {
          id: "wash-" + Date.now(),
          receipt_number: `RC-${new Date().toISOString().slice(2, 4)}${String(current.length + 1).padStart(4, "0")}`,
          started_at: new Date().toISOString(),
          commission_amount: Math.round(wash.price * 0.2),
          ...wash,
          completed_at: wash.completed_at || null,
          status: wash.status || "in_progress",
        };
        setLocal(STORAGE_KEYS.WASH_TRANSACTIONS, [fallbackWash, ...current]);

        if (wash.washer_id && wash.soap_used_ml) {
          const washerStocks = getLocal<Record<string, number>>(STORAGE_KEYS.WASHERS_STOCK, {
            "w-1": 750,
            "w-2": 540,
            "w-3": 180,
            "w-4": 620,
          });
          washerStocks[wash.washer_id] = Math.max(0, (washerStocks[wash.washer_id] ?? 800) - wash.soap_used_ml);
          setLocal(STORAGE_KEYS.WASHERS_STOCK, washerStocks);
        }

        return fallbackWash;
      }
    );
  },

  async updateWashStatus(id: string, status: WashStatus): Promise<void> {
    const isCompleted = status === "completed";
    await supabaseCall(
      (async () => {
        const supabase = createClient();
        const updatePayload: any = { status };
        if (isCompleted) {
          updatePayload.completed_at = new Date().toISOString();
        }
        const { error } = await supabase
          .from("wash_transactions")
          .update(updatePayload)
          .eq("id", id);
        return { data: null, error };
      })(),
      () => {
        const washes = getLocal<WashTransaction[]>(STORAGE_KEYS.WASH_TRANSACTIONS, SEED_WASHES);
        const updated = washes.map((w) => {
          if (w.id === id) {
            return {
              ...w,
              status,
              completed_at: isCompleted ? (w.completed_at || new Date().toISOString()) : w.completed_at,
            };
          }
          return w;
        });
        setLocal(STORAGE_KEYS.WASH_TRANSACTIONS, updated);
        return undefined;
      }
    );
  },

  // ── SOAP REQUESTS ──────────────────────────────────────────
  async getSoapRequests(): Promise<SoapRequest[]> {
    return supabaseCall<SoapRequest[]>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase
          .from("soap_requests")
          .select(
            "id, request_number, quantity_requested, quantity_approved, status, notes, created_at, washer_id, inventory_id, profiles(full_name), inventory(product_name)"
          )
          .order("created_at", { ascending: false });
        if (data) {
          const mapped: SoapRequest[] = (data as any[]).map((r) => ({
            id: r.id,
            request_number: r.request_number || "SR-" + r.id.slice(0, 5),
            washer_id: r.washer_id,
            washer_name: r.profiles?.full_name || r.washer_name || "Washer",
            inventory_id: r.inventory_id,
            product_name: r.inventory?.product_name || r.product_name || "Largo Detergent",
            quantity_requested: Number(r.quantity_requested || 0),
            quantity_approved: r.quantity_approved ? Number(r.quantity_approved) : null,
            status: r.status || "pending",
            notes: r.notes,
            created_at: r.created_at,
          }));
          setLocal(STORAGE_KEYS.SOAP_REQUESTS, mapped);
          return { data: mapped, error };
        }
        return { data: null, error };
      })(),
      () => getLocal<SoapRequest[]>(STORAGE_KEYS.SOAP_REQUESTS, SEED_REQUESTS)
    );
  },

  async createSoapRequest(req: {
    washer_id: string;
    washer_name: string;
    inventory_id: string;
    product_name: string;
    quantity_requested: number;
    notes?: string;
  }): Promise<SoapRequest> {
    return supabaseCall<SoapRequest>(
      (async () => {
        const supabase = createClient();

        let washerId = req.washer_id;
        const isUUID = washerId && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(washerId);
        if (!isUUID) {
          const { data: prof } = await supabase.from("profiles").select("id").limit(1).maybeSingle();
          if (prof) washerId = prof.id;
        }

        const { data, error } = await supabase
          .from("soap_requests")
          .insert({
            washer_id: washerId,
            inventory_id: req.inventory_id,
            quantity_requested: Number(req.quantity_requested),
            notes: req.notes || null,
            status: "pending",
          })
          .select()
          .single();

        if (data) {
          const created: SoapRequest = {
            id: data.id,
            request_number: data.request_number,
            washer_id: req.washer_id,
            washer_name: req.washer_name,
            inventory_id: req.inventory_id,
            product_name: req.product_name,
            quantity_requested: Number(data.quantity_requested),
            quantity_approved: null,
            status: "pending",
            notes: data.notes,
            created_at: data.created_at,
          };
          const current = getLocal<SoapRequest[]>(STORAGE_KEYS.SOAP_REQUESTS, SEED_REQUESTS);
          setLocal(STORAGE_KEYS.SOAP_REQUESTS, [created, ...current.filter((r) => r.id !== created.id)]);
          return { data: created, error: null };
        }
        return { data: null, error };
      })(),
      () => {
        const current = getLocal<SoapRequest[]>(STORAGE_KEYS.SOAP_REQUESTS, SEED_REQUESTS);
        const fallbackReq: SoapRequest = {
          id: "rq-" + Date.now(),
          request_number: `RQ-${1040 + current.length + 1}`,
          status: "pending",
          quantity_approved: null,
          created_at: new Date().toISOString(),
          ...req,
        };
        setLocal(STORAGE_KEYS.SOAP_REQUESTS, [fallbackReq, ...current]);
        return fallbackReq;
      }
    );
  },

  async decideSoapRequest(
    id: string,
    status: "approved" | "rejected",
    approvedQty?: number
  ): Promise<void> {
    await supabaseCall(
      (async () => {
        const supabase = createClient();
        const current = getLocal<SoapRequest[]>(STORAGE_KEYS.SOAP_REQUESTS, SEED_REQUESTS);
        const target = current.find((r) => r.id === id);
        if (!target) return { data: null, error: null };
        const qty = status === "approved" ? (approvedQty ?? target.quantity_requested) : null;
        const updatedReqs = current.map((r) =>
          r.id === id ? { ...r, status, quantity_approved: qty, decided_at: new Date().toISOString() } : r
        );
        setLocal(STORAGE_KEYS.SOAP_REQUESTS, updatedReqs);

        if (status === "approved" && qty) {
          // 1. Deduct from main store inventory
          const inv = getLocal<InventoryItem[]>(STORAGE_KEYS.INVENTORY, SEED_INVENTORY);
          const updatedInv = inv.map((item) => {
            if (item.id === target.inventory_id || item.product_name === target.product_name) {
              const newTotal = Math.max(0, item.total_ml - qty);
              const st: "ok" | "low" | "critical" =
                newTotal <= item.min_stock_ml * 0.4 ? "critical" : newTotal <= item.min_stock_ml ? "low" : "ok";
              return { ...item, total_ml: newTotal, status: st };
            }
            return item;
          });
          setLocal(STORAGE_KEYS.INVENTORY, updatedInv);

          // 2. Add to washer's stock
          const washerStocks = getLocal<Record<string, number>>(STORAGE_KEYS.WASHERS_STOCK, {
            "w-1": 750,
            "w-2": 540,
            "w-3": 180,
            "w-4": 620,
          });
          washerStocks[target.washer_id] = (washerStocks[target.washer_id] ?? 0) + qty;
          setLocal(STORAGE_KEYS.WASHERS_STOCK, washerStocks);
        }

        await supabase
          .from("soap_requests")
          .update({ status, quantity_approved: qty, decided_at: new Date().toISOString() })
          .eq("id", id);
        return { data: null, error: null };
      })(),
      () => {
        const current = getLocal<SoapRequest[]>(STORAGE_KEYS.SOAP_REQUESTS, SEED_REQUESTS);
        const target = current.find((r) => r.id === id);
        if (!target) return undefined;
        const qty = status === "approved" ? (approvedQty ?? target.quantity_requested) : null;
        const updatedReqs = current.map((r) =>
          r.id === id ? { ...r, status, quantity_approved: qty, decided_at: new Date().toISOString() } : r
        );
        setLocal(STORAGE_KEYS.SOAP_REQUESTS, updatedReqs);

        if (status === "approved" && qty) {
          const inv = getLocal<InventoryItem[]>(STORAGE_KEYS.INVENTORY, SEED_INVENTORY);
          const updatedInv = inv.map((item) => {
            if (item.id === target.inventory_id || item.product_name === target.product_name) {
              const newTotal = Math.max(0, item.total_ml - qty);
              const st: "ok" | "low" | "critical" =
                newTotal <= item.min_stock_ml * 0.4 ? "critical" : newTotal <= item.min_stock_ml ? "low" : "ok";
              return { ...item, total_ml: newTotal, status: st };
            }
            return item;
          });
          setLocal(STORAGE_KEYS.INVENTORY, updatedInv);

          const washerStocks = getLocal<Record<string, number>>(STORAGE_KEYS.WASHERS_STOCK, {
            "w-1": 750,
            "w-2": 540,
            "w-3": 180,
            "w-4": 620,
          });
          washerStocks[target.washer_id] = (washerStocks[target.washer_id] ?? 0) + qty;
          setLocal(STORAGE_KEYS.WASHERS_STOCK, washerStocks);
        }
        return undefined;
      }
    );
  },

  // ── EXPENSES ───────────────────────────────────────────────
  async getExpenses(): Promise<Expense[]> {
    return supabaseCall<Expense[]>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase.from("expenses").select("*").order("incurred_on", { ascending: false });
        if (data && !error) {
          setLocal(STORAGE_KEYS.EXPENSES, data);
        }
        return { data: data as Expense[] | null, error };
      })(),
      () => getLocal<Expense[]>(STORAGE_KEYS.EXPENSES, SEED_EXPENSES)
    );
  },

  async createExpense(expense: Omit<Expense, "id" | "created_at">): Promise<Expense> {
    return supabaseCall<Expense>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase
          .from("expenses")
          .insert({
            category: expense.category,
            amount: Number(expense.amount),
            description: expense.description || null,
            incurred_on: expense.incurred_on || new Date().toISOString().slice(0, 10),
          })
          .select()
          .single();

        if (data) {
          const created: Expense = {
            id: data.id,
            category: data.category,
            amount: Number(data.amount),
            description: data.description,
            incurred_on: data.incurred_on,
            created_at: data.created_at,
          };
          const list = getLocal<Expense[]>(STORAGE_KEYS.EXPENSES, SEED_EXPENSES);
          setLocal(STORAGE_KEYS.EXPENSES, [created, ...list.filter((e) => e.id !== created.id)]);
          return { data: created, error: null };
        }
        return { data: null, error };
      })(),
      () => {
        const fallbackExp: Expense = {
          id: "exp-" + Date.now(),
          created_at: new Date().toISOString(),
          ...expense,
        };
        const list = getLocal<Expense[]>(STORAGE_KEYS.EXPENSES, SEED_EXPENSES);
        setLocal(STORAGE_KEYS.EXPENSES, [fallbackExp, ...list]);
        return fallbackExp;
      }
    );
  },

  async deleteExpense(id: string): Promise<void> {
    await supabaseCall(
      (async () => {
        const supabase = createClient();
        const { error } = await supabase.from("expenses").delete().eq("id", id);
        return { data: null, error };
      })(),
      () => {
        const list = getLocal<Expense[]>(STORAGE_KEYS.EXPENSES, SEED_EXPENSES);
        setLocal(STORAGE_KEYS.EXPENSES, list.filter((e) => e.id !== id));
        return undefined;
      }
    );
  },

  // ── WASHER & STAFF STATS ───────────────────────────────────
  async getWashersStock(): Promise<
    { id: string; name: string; soap: number; carsToday: number; revenueToday: number; commissionToday: number; phone?: string }[]
  > {
    return supabaseCall(
      (async () => {
        const supabase = createClient();
        const [washes, profilesRes] = await Promise.all([
          DataStore.getWashTransactions(),
          supabase.from("profiles").select("*").order("full_name"),
        ]);

        const today = new Date().toISOString().slice(0, 10);
        const todayWashes = washes.filter((w) => w.started_at.startsWith(today) && w.status !== "cancelled");
        const staff = profilesRes.data || [];
        const washerStocks = getLocal<Record<string, number>>(STORAGE_KEYS.WASHERS_STOCK, {});

        const list = staff.map((p: any) => {
          const myToday = todayWashes.filter((tw) => tw.washer_id === p.id || tw.washer_name === p.full_name);
          const revenueToday = myToday.reduce((s, tw) => s + tw.price, 0);
          return {
            id: p.id,
            name: p.full_name,
            soap: washerStocks[p.id] ?? 800,
            carsToday: myToday.length,
            revenueToday,
            commissionToday: Math.round(revenueToday * 0.2), // 20% commission
            phone: p.phone || undefined,
          };
        });
        return { data: list, error: null };
      })(),
      () => []
    );
  },

  async getStaff(): Promise<Profile[]> {
    return supabaseCall<Profile[]>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase.from("profiles").select("*").order("full_name");
        return { data: data as Profile[] | null, error };
      })(),
      () => getLocal<Profile[]>(STORAGE_KEYS.STAFF, SEED_STAFF)
    );
  },

  // ── SHIFT CASH SETTLEMENT & DRAWER RECONCILIATION ─────────
  async getShiftSettlement() {
    const today = new Date().toISOString().slice(0, 10);
    const [washes, expenses] = await Promise.all([
      this.getWashTransactions(today, today),
      this.getExpenses(),
    ]);

    const todayExpenses = expenses.filter((e) => e.incurred_on.startsWith(today));
    const totalExpenses = todayExpenses.reduce((s, e) => s + Number(e.amount), 0);

    let cashTotal = 0;
    let telebirrTotal = 0;
    let cbeBirrTotal = 0;
    let cardTotal = 0;
    let accountTotal = 0;
    let totalCommission = 0;

    for (const w of washes) {
      if (w.status === "cancelled") continue;
      const amt = Number(w.price || 0);
      totalCommission += w.commission_amount || Math.round(amt * 0.2);

      switch (w.payment_method) {
        case "cash":
          cashTotal += amt;
          break;
        case "telebirr":
          telebirrTotal += amt;
          break;
        case "cbe_birr":
          cbeBirrTotal += amt;
          break;
        case "card":
          cardTotal += amt;
          break;
        case "account":
          accountTotal += amt;
          break;
      }
    }

    const totalRevenue = cashTotal + telebirrTotal + cbeBirrTotal + cardTotal + accountTotal;
    const netCashInDrawer = Math.max(0, cashTotal - totalExpenses - totalCommission);

    return {
      today,
      washesCount: washes.length,
      totalRevenue,
      cashTotal,
      telebirrTotal,
      cbeBirrTotal,
      cardTotal,
      accountTotal,
      totalCommission,
      totalExpenses,
      netCashInDrawer,
    };
  },

  // ── CHEMICAL THEFT & VARIANCE TRACKER ─────────────────────
  async getChemicalVariance() {
    const today = new Date().toISOString().slice(0, 10);
    const [washes, requests] = await Promise.all([
      this.getWashTransactions(today, today),
      this.getSoapRequests(),
    ]);

    const activeWashes = washes.filter((w) => w.status !== "cancelled");
    const theoreticalSoapUsed = activeWashes.reduce((sum, w) => sum + (w.soap_used_ml || 0), 0);

    const todayApprovedReqs = requests.filter(
      (r) => r.created_at.startsWith(today) && r.status === "approved"
    );
    const actualSoapDispensed = todayApprovedReqs.reduce(
      (sum, r) => sum + (r.quantity_approved || r.quantity_requested || 0),
      0
    );

    const varianceMl = actualSoapDispensed - theoreticalSoapUsed;
    const isExcessive = varianceMl > 500;
    const isUnderuse = varianceMl < -300;

    return {
      carsWashed: activeWashes.length,
      theoreticalSoapUsed,
      actualSoapDispensed,
      varianceMl,
      status: isExcessive ? "excessive_loss" : isUnderuse ? "possible_underwash" : "normal",
    };
  },

  // ── LOYALTY & REWARDS ────────────────────────────────────
  async getLoyaltyStatus(plate: string) {
    if (!plate || plate.trim().length < 3) return null;
    const cleanPlate = plate.trim().toUpperCase();
    const washes = await this.getWashTransactions();
    const plateWashes = washes.filter(
      (w) => w.plate?.toUpperCase() === cleanPlate && w.status === "completed"
    );

    const count = plateWashes.length;
    const isFifthWash = count > 0 && count % 5 === 4; // next is 5th
    const isTenthWash = count > 0 && count % 10 === 9; // next is 10th

    return {
      plate: cleanPlate,
      totalPastWashes: count,
      nextDiscount: isTenthWash ? "FREE WASH (10th Visit VIP)" : isFifthWash ? "50% OFF (5th Loyalty Visit)" : null,
      rewardActive: isFifthWash || isTenthWash,
    };
  },

  // ── SERVICES & CATALOG ─────────────────────────────────────
  getServices(): WashService[] {
    return DEFAULT_WASH_SERVICES;
  },

  getVehicleTypes() {
    return DEFAULT_VEHICLE_TYPES;
  },

  async fetchServices(): Promise<WashService[]> {
    return supabaseCall<WashService[]>(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase.from("wash_services").select("*").order("name");
        return { data: data && data.length > 0 ? (data as WashService[]) : DEFAULT_WASH_SERVICES, error };
      })(),
      () => DEFAULT_WASH_SERVICES
    );
  },

  async fetchVehicleTypes() {
    return supabaseCall(
      (async () => {
        const supabase = createClient();
        const { data, error } = await supabase.from("vehicle_types").select("*").order("default_price");
        return { data: data && data.length > 0 ? data : DEFAULT_VEHICLE_TYPES, error };
      })(),
      () => DEFAULT_VEHICLE_TYPES
    );
  },
};