// WashOS Master Mock & Fallback Seed Data
// Calibrated to Ethiopian Standards: LARGO detergent (5L = 940 ETB / 188 ETB/L)
import { VehicleType, WashService, InventoryItem, Supplier, PurchaseOrder, Profile, Expense, Customer, SoapRequest } from "./types";

export const VEHICLE_TYPES: VehicleType[] = [
  {
    id: "small",
    name: "Light Vehicle",
    examples: "Automobile, Minibus, Pickup, Vitz, Corolla",
    standard_minutes: 45,
    workers_required: 2,
    default_soap_ml: 180,
    detergent_cost_etb: 33.84,
    default_price: 350,
    color: "#2dd4c8",
  },
  {
    id: "medium",
    name: "Medium Vehicle",
    examples: "Sino Truck, Isuzu, Mid Bus, Land Cruiser",
    standard_minutes: 120,
    workers_required: 2,
    default_soap_ml: 250,
    detergent_cost_etb: 47.0,
    default_price: 900,
    color: "#f59e0b",
  },
  {
    id: "large",
    name: "Heavy Vehicle",
    examples: "Trailer, Fuel Tanker, Heavy Machinery",
    standard_minutes: 180,
    workers_required: 2,
    default_soap_ml: 500,
    detergent_cost_etb: 94.0,
    default_price: 1800,
    color: "#a78bfa",
  },
];

export const WASH_SERVICES: WashService[] = [
  {
    id: "exterior",
    name: "Standard Exterior Wash",
    category: "standard",
    description: "High-pressure foam wash, wheel clean, hand dry",
    price_small: 350,
    price_medium: 900,
    price_large: 1800,
    extra_soap_ml: 0,
    active: true,
  },
  {
    id: "full_wash",
    name: "Full Wash (Body + Engine + Underbody)",
    category: "standard",
    description: "Full body shampoo, undercarriage degrease, engine bay wash",
    price_small: 550,
    price_medium: 1400,
    price_large: 2600,
    extra_soap_ml: 80,
    active: true,
  },
  {
    id: "engine_steam",
    name: "Engine Steam Clean",
    category: "addon",
    description: "High-temp degreasing and electronic component care",
    price_small: 250,
    price_medium: 450,
    price_large: 700,
    extra_soap_ml: 50,
    active: true,
  },
  {
    id: "interior_detail",
    name: "Interior Deep Clean & Vacuum",
    category: "addon",
    description: "Seat extraction, dashboard UV protectant, carpet shampoo",
    price_small: 300,
    price_medium: 600,
    price_large: 900,
    extra_soap_ml: 40,
    active: true,
  },
  {
    id: "wax_polish",
    name: "Hand Wax & Paint Sealant",
    category: "addon",
    description: "Carnauba wax coating for gloss finish and water repellency",
    price_small: 350,
    price_medium: 700,
    price_large: 1100,
    extra_soap_ml: 30,
    active: true,
  },
  {
    id: "tire_shine",
    name: "Tire & Trim Dressing",
    category: "addon",
    description: "Silicone-free deep black tire shine and UV protection",
    price_small: 100,
    price_medium: 200,
    price_large: 300,
    extra_soap_ml: 20,
    active: true,
  },
];

export const SUPPLIERS: Supplier[] = [
  {
    id: "sup-1",
    name: "Chemtech PLC",
    contact: "+251 11 234 5678",
    email: "sales@chemtech.et",
    products: "LARGO Foam Shampoo, Glass Cleaner, Engine Degreaser",
    address: "Bole Sub-city, Woreda 03, Addis Ababa",
    active: true,
  },
  {
    id: "sup-2",
    name: "AutoCare Import & Dist.",
    contact: "+251 11 345 6789",
    email: "info@autocare.et",
    products: "Tire Shine Gel, Carnauba Wax, Microfiber Towels",
    address: "Nifas Silk Lafto, Addis Ababa",
    active: true,
  },
  {
    id: "sup-3",
    name: "Habesha Chemical Industries",
    contact: "+251 11 456 7890",
    email: "contact@habeshachem.com",
    products: "Heavy Duty Degreaser, Acid Wash, Upholstery Cleaner",
    address: "Kaliti Industrial Zone, Addis Ababa",
    active: true,
  },
];

export const INVENTORY: InventoryItem[] = [
  {
    id: "inv-1",
    product_name: "LARGO Detergent Concentrate",
    category: "Soap",
    total_ml: 38500,
    min_stock_ml: 10000,
    supplier: "Chemtech PLC",
    supplier_id: "sup-1",
    batch_number: "BATCH-2026-04",
    expiry_date: "2027-04-10",
    unit_cost: 0.188,
    cost: 9400,
    status: "ok",
  },
  {
    id: "inv-2",
    product_name: "Tire Shine Silicone Gel",
    category: "Finishing",
    total_ml: 12400,
    min_stock_ml: 6000,
    supplier: "AutoCare Import & Dist.",
    supplier_id: "sup-2",
    batch_number: "BATCH-2026-03",
    expiry_date: "2027-09-15",
    unit_cost: 0.32,
    cost: 4800,
    status: "ok",
  },
  {
    id: "inv-3",
    product_name: "Crystal Clear Glass Cleaner",
    category: "Interior",
    total_ml: 14800,
    min_stock_ml: 5000,
    supplier: "Chemtech PLC",
    supplier_id: "sup-1",
    batch_number: "BATCH-2026-05",
    expiry_date: "2027-11-02",
    unit_cost: 0.15,
    cost: 3000,
    status: "ok",
  },
  {
    id: "inv-4",
    product_name: "Heavy Duty Engine Degreaser",
    category: "Soap",
    total_ml: 3200,
    min_stock_ml: 8000,
    supplier: "Habesha Chemical Industries",
    supplier_id: "sup-3",
    batch_number: "BATCH-2026-01",
    expiry_date: "2026-10-20",
    unit_cost: 0.22,
    cost: 3300,
    status: "critical",
  },
  {
    id: "inv-5",
    product_name: "Carnauba Liquid Gloss Wax",
    category: "Finishing",
    total_ml: 8500,
    min_stock_ml: 4000,
    supplier: "AutoCare Import & Dist.",
    supplier_id: "sup-2",
    batch_number: "BATCH-2026-04",
    expiry_date: "2027-08-18",
    unit_cost: 0.45,
    cost: 4500,
    status: "ok",
  },
];

export const PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po-1",
    po_number: "PO-1001",
    supplier_id: "sup-1",
    supplier_name: "Chemtech PLC",
    inventory_id: "inv-1",
    product_name: "LARGO Detergent Concentrate",
    qty_ml: 50000,
    unit_cost: 0.188,
    total_cost: 9400,
    status: "received",
    ordered_at: "2026-07-28T09:00:00Z",
    received_at: "2026-07-31T14:30:00Z",
    notes: "50L bulk barrel delivery",
  },
  {
    id: "po-2",
    po_number: "PO-1002",
    supplier_id: "sup-2",
    supplier_name: "AutoCare Import & Dist.",
    inventory_id: "inv-2",
    product_name: "Tire Shine Silicone Gel",
    qty_ml: 15000,
    unit_cost: 0.32,
    total_cost: 4800,
    status: "received",
    ordered_at: "2026-08-04T10:15:00Z",
    received_at: "2026-08-07T11:00:00Z",
    notes: "Restocked for weekend rush",
  },
  {
    id: "po-3",
    po_number: "PO-1003",
    supplier_id: "sup-3",
    supplier_name: "Habesha Chemical Industries",
    inventory_id: "inv-4",
    product_name: "Heavy Duty Engine Degreaser",
    qty_ml: 20000,
    unit_cost: 0.22,
    total_cost: 4400,
    status: "pending",
    ordered_at: "2026-08-11T08:30:00Z",
    received_at: null,
    notes: "Urgent: Degreaser stock critical",
  },
];

export const WASHERS = [
  { id: "w-1", name: "Yonas Bekele", soap: 750, carsToday: 7, revenueToday: 2850, avgEff: 96, phone: "+251 91 234 5678" },
  { id: "w-2", name: "Selam Girma", soap: 540, carsToday: 5, revenueToday: 1950, avgEff: 92, phone: "+251 92 345 6789" },
  { id: "w-3", name: "Dawit Alemu", soap: 180, carsToday: 4, revenueToday: 3600, avgEff: 89, phone: "+251 93 456 7890" },
  { id: "w-4", name: "Hana Tesfaye", soap: 620, carsToday: 6, revenueToday: 2450, avgEff: 98, phone: "+251 94 567 8901" },
];

export const STAFF: Profile[] = [
  { id: "w-1", full_name: "Yonas Bekele", role: "washer", phone: "+251 91 234 5678", active: true, created_at: "2024-03-12" },
  { id: "w-2", full_name: "Selam Girma", role: "washer", phone: "+251 92 345 6789", active: true, created_at: "2024-06-01" },
  { id: "w-3", full_name: "Dawit Alemu", role: "washer", phone: "+251 93 456 7890", active: true, created_at: "2025-01-15" },
  { id: "w-4", full_name: "Hana Tesfaye", role: "washer", phone: "+251 94 567 8901", active: true, created_at: "2025-02-20" },
  { id: "s-5", full_name: "Ezra Mulugeta", role: "manager", phone: "+251 91 111 2222", active: true, created_at: "2023-11-01" },
  { id: "s-6", full_name: "Liya Hailu", role: "store_keeper", phone: "+251 92 222 3333", active: true, created_at: "2024-08-10" },
  { id: "s-7", full_name: "Abebe Admin", role: "administrator", phone: "+251 91 000 1111", active: true, created_at: "2023-01-01" },
];

export const CUSTOMERS: Customer[] = [
  { id: "c-1", full_name: "Alemayehu Tadesse", phone: "+251 91 123 4567", notes: "VIP Customer · Prefers full wash + engine steam", created_at: "2025-04-10", vehicle_count: 1, total_spent: 4200, last_visit: "2026-08-12" },
  { id: "c-2", full_name: "Bethlehem Haile", phone: "+251 92 234 5678", notes: "Weekly regular (Hyundai Tucson)", created_at: "2025-05-15", vehicle_count: 1, total_spent: 2800, last_visit: "2026-08-11" },
  { id: "c-3", full_name: "Kassahun Worku", phone: "+251 93 345 6789", notes: "Sino Truck fleet owner · Monthly account", created_at: "2025-06-01", vehicle_count: 3, total_spent: 12600, last_visit: "2026-08-13" },
  { id: "c-4", full_name: "Samrawit Girma", phone: "+251 94 456 7890", notes: "Toyota Vitz · Extra interior vacuum care", created_at: "2025-07-20", vehicle_count: 1, total_spent: 1750, last_visit: "2026-08-10" },
  { id: "c-5", full_name: "Dawit Kebede", phone: "+251 91 567 8901", notes: "Trailer logistics operator", created_at: "2025-08-01", vehicle_count: 2, total_spent: 7200, last_visit: "2026-08-12" },
];

export const REQUESTS: SoapRequest[] = [
  { id: "rq-1", request_number: "RQ-1042", washer_name: "Dawit Alemu", washer_id: "w-3", product_name: "LARGO Detergent Concentrate", inventory_id: "inv-1", quantity_requested: 500, quantity_approved: null, status: "pending", notes: "Medium Truck wash prep", created_at: "2026-08-13T08:30:00Z" },
  { id: "rq-2", request_number: "RQ-1041", washer_name: "Selam Girma", washer_id: "w-2", product_name: "Heavy Duty Engine Degreaser", inventory_id: "inv-4", quantity_requested: 300, quantity_approved: null, status: "pending", notes: "Engine steam bay", created_at: "2026-08-13T09:15:00Z" },
  { id: "rq-3", request_number: "RQ-1040", washer_name: "Yonas Bekele", washer_id: "w-1", product_name: "LARGO Detergent Concentrate", inventory_id: "inv-1", quantity_requested: 600, quantity_approved: 600, status: "approved", notes: "Morning batch refill", created_at: "2026-08-12T14:00:00Z" },
  { id: "rq-4", request_number: "RQ-1039", washer_name: "Hana Tesfaye", washer_id: "w-4", product_name: "Crystal Clear Glass Cleaner", inventory_id: "inv-3", quantity_requested: 400, quantity_approved: 400, status: "approved", notes: "Interior detailing bay", created_at: "2026-08-12T11:20:00Z" },
];

export const EXPENSES: Expense[] = [
  { id: "exp-1", category: "utilities", amount: 4200, description: "Water utility bill for wash bays", incurred_on: "2026-08-03", created_at: "2026-08-03T10:00:00Z" },
  { id: "exp-2", category: "maintenance", amount: 3500, description: "High-pressure pump hose & nozzle replacement", incurred_on: "2026-08-07", created_at: "2026-08-07T12:00:00Z" },
  { id: "exp-3", category: "inventory_cost", amount: 9400, description: "LARGO 50L bulk purchase payment", incurred_on: "2026-08-02", created_at: "2026-08-02T09:30:00Z" },
  { id: "exp-4", category: "payroll", amount: 18500, description: "Weekly washer commission and staff base allowances", incurred_on: "2026-08-10", created_at: "2026-08-10T17:00:00Z" },
  { id: "exp-5", category: "other", amount: 1200, description: "Customer lounge refreshments & supplies", incurred_on: "2026-08-12", created_at: "2026-08-12T15:00:00Z" },
];

export const WASH_HISTORY = [
  {
    id: "tx-1",
    receipt_number: "REC-10041",
    plate: "AA-A-12345",
    vehicle_type_id: "small" as const,
    washer_id: "w-1",
    washer_name: "Yonas Bekele",
    customer_name: "Alemayehu Tadesse",
    price: 350,
    soap_used_ml: 180,
    payment_method: "telebirr" as const,
    payment_status: "paid" as const,
    services: ["Standard Exterior Wash"],
    bay_number: 1,
    status: "completed" as const,
    started_at: "2026-08-13T08:15:00Z",
    completed_at: "2026-08-13T08:55:00Z",
    actual_minutes: 40,
  },
  {
    id: "tx-2",
    receipt_number: "REC-10042",
    plate: "AA-B-67890",
    vehicle_type_id: "medium" as const,
    washer_id: "w-2",
    washer_name: "Selam Girma",
    customer_name: "Bethlehem Haile",
    price: 900,
    soap_used_ml: 250,
    payment_method: "cash" as const,
    payment_status: "paid" as const,
    services: ["Standard Exterior Wash", "Tire & Trim Dressing"],
    bay_number: 2,
    status: "completed" as const,
    started_at: "2026-08-13T09:00:00Z",
    completed_at: "2026-08-13T10:45:00Z",
    actual_minutes: 105,
  },
  {
    id: "tx-3",
    receipt_number: "REC-10043",
    plate: "AA-C-11111",
    vehicle_type_id: "small" as const,
    washer_id: "w-4",
    washer_name: "Hana Tesfaye",
    customer_name: "Samrawit Girma",
    price: 650,
    soap_used_ml: 220,
    payment_method: "cbe_birr" as const,
    payment_status: "paid" as const,
    services: ["Standard Exterior Wash", "Interior Deep Clean & Vacuum"],
    bay_number: 3,
    status: "completed" as const,
    started_at: "2026-08-13T10:20:00Z",
    completed_at: "2026-08-13T11:05:00Z",
    actual_minutes: 45,
  },
  {
    id: "tx-4",
    receipt_number: "REC-10044",
    plate: "AA-D-22222",
    vehicle_type_id: "large" as const,
    washer_id: "w-3",
    washer_name: "Dawit Alemu",
    customer_name: "Dawit Kebede",
    price: 1800,
    soap_used_ml: 500,
    payment_method: "account" as const,
    payment_status: "paid" as const,
    services: ["Standard Exterior Wash"],
    bay_number: 4,
    status: "completed" as const,
    started_at: "2026-08-13T11:00:00Z",
    completed_at: "2026-08-13T13:40:00Z",
    actual_minutes: 160,
  },
  {
    id: "tx-5",
    receipt_number: "REC-10045",
    plate: "AA-E-33333",
    vehicle_type_id: "medium" as const,
    washer_id: "w-1",
    washer_name: "Yonas Bekele",
    customer_name: "Kassahun Worku",
    price: 1400,
    soap_used_ml: 330,
    payment_method: "telebirr" as const,
    payment_status: "paid" as const,
    services: ["Full Wash (Body + Engine + Underbody)"],
    bay_number: 1,
    status: "completed" as const,
    started_at: "2026-08-13T12:00:00Z",
    completed_at: "2026-08-13T13:50:00Z",
    actual_minutes: 110,
  },
];

export const REVENUE_TREND = [
  { day: "Mon", revenue: 16400, expenses: 5200 },
  { day: "Tue", revenue: 18900, expenses: 4600 },
  { day: "Wed", revenue: 17200, expenses: 5100 },
  { day: "Thu", revenue: 21500, expenses: 6100 },
  { day: "Fri", revenue: 26800, expenses: 6400 },
  { day: "Sat", revenue: 34200, expenses: 7200 },
  { day: "Sun", revenue: 29500, expenses: 6800 },
];
